mybatis:
  config-location: classpath:mybatis/mybatis-config.xml

spring:
  datasource:
    test1:
      jdbc-url: "jdbc:mysql://localhost:3306/test1?serverTimezone=UTC\
        &useUnicode=true&characterEncoding=utf-8&useSSL=true"
      username: root
      password: password
      driver-class-name: com.mysql.cj.jdbc.Driver
    test2:
      jdbc-url: "jdbc:mysql://localhost:3306/test2?serverTimezone=UTC\
        &useUnicode=true&characterEncoding=utf-8&useSSL=true"
      username: root
      password: password
      driver-class-name: com.mysql.cj.jdbc.Driver
